name: 20 Minute Blues Jams
favicon: null
layout_spectrum: 0.5061
typography_spectrum: 0.25377
title: "Johnny London's Blues Jam Tracks"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a97c0'
    - '#120f08'
    - '#c2c2a8'
    - '#fffff3'
    - '#676d65'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
